/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mock.ia;

/**
 *
 * @author tito
 */
public class Advanced extends javax.swing.JFrame {

    private Player player;
    private SearchParser search;
    
    /**
     * Creates new form Advanced
     */
    public Advanced(Player player, SearchParser search) throws Exception {
        this.player = player;
        this.search = search;
        initComponents();
        
    }

    private Advanced() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws Exception {

        playerName = new javax.swing.JLabel();
        teamName = new javax.swing.JLabel();
        playerNum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        String output = "";
        String[][] data = new String[2][10];

        String[] columns = {"eFG%", "TS%", "ORB%", "DRB%", "TRB%", "AST%", "STL%", "BLK%", "TOV%", "USG%"};
        data[0] = columns;
        data[1] = player.advanced();

        for (int row = 0; row<data.length; row++)
        {
            for (int column = 0; column<data[row].length; column++)
            {
                output = output + data[row][column] + "\t       ";
            }
            output = output + "\n";
        }
        advancedStats = new javax.swing.JTextArea(output);
        jScrollPane2 = new javax.swing.JScrollPane();
        String result = "";
        String[][] dataSet = new String[2][9];
        String[] categories = {"PPG", "APG", "RPG", "OREB", "DREB", "MPG", "STLPG", "BLKPG", "TOPG"};
        dataSet[0] = categories;
        dataSet[1] = player.per36();
        for (int row = 0; row<dataSet.length; row++)
        {
            for (int column = 0; column<dataSet[row].length; column++)
            {
                result = result + dataSet[row][column] + "\t       ";
            }
            result = result + "\n";
        }
        per36 = new javax.swing.JTextArea(result);
        back = new javax.swing.JButton();
        advancedLabel = new javax.swing.JLabel();
        per36label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        String val = "";
        String[][] basicStats = new String[2][9];
        basicStats[0] = categories;
        basicStats[1] = player.averagesPlayer();
        for (int row = 0; row<basicStats.length; row++)
        {
            for (int column = 0; column<basicStats[row].length; column++)
            {
                val = val + basicStats[row][column] + "\t       ";
            }
            val = val + "\n";
        }
        averages = new javax.swing.JTextArea(val);
        seasonAverages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerName.setFont(new java.awt.Font("Lucida Grande", 0, 26)); // NOI18N
        playerName.setText(player.getName());

        teamName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        teamName.setText(player.getTeam().getName());

        playerNum.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        playerNum.setText(""+player.getNum());

        advancedStats.setEditable(false);
        advancedStats.setColumns(10);
        advancedStats.setRows(1);
        jScrollPane1.setViewportView(advancedStats);

        per36.setEditable(false);
        per36.setColumns(10);
        per36.setRows(1);
        jScrollPane2.setViewportView(per36);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        advancedLabel.setText("Advanced Stats");

        per36label.setText("Per 36 Minutes");

        averages.setEditable(false);
        averages.setColumns(10);
        averages.setRows(1);
        jScrollPane3.setViewportView(averages);

        seasonAverages.setText("Season Averages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seasonAverages)
                    .addComponent(per36label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(advancedLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(teamName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(playerNum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(back))))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(advancedLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(per36label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seasonAverages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the object and disposes of it
     */
    public void close()
    {
        this.setVisible(false);
        search.getErrorLabel().setText("");
        this.dispose();
    }
    
    /**
     * Goes back to the search object that initialized this instance
     * @param evt 
     */
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        search.setVisible(true);
        close();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Advanced().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancedLabel;
    private javax.swing.JTextArea advancedStats;
    private javax.swing.JTextArea averages;
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea per36;
    private javax.swing.JLabel per36label;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel playerNum;
    private javax.swing.JLabel seasonAverages;
    private javax.swing.JLabel teamName;
    // End of variables declaration//GEN-END:variables
}
