/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mock.ia;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tito
 */
public class Black extends javax.swing.JFrame {

    /**
     * Creates new form Black
     */
    public Black() throws Exception{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws Exception {

        backButton = new javax.swing.JButton();
        TeamsText = new javax.swing.JLabel();
        players = new javax.swing.JLabel();
        advanced = new javax.swing.JLabel();
        BlackLogo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        String output = "";
        String[][] data = new String[Database.Main.length("black")+1][10];
        GUIForm GUI = new GUIForm();
        String[] columns = {"Name", "Position", "#", "PPG", "APG", "RPG", "MPG", "STLPG", "BLKPG", "TOPG"};
        data[0] = columns;

        for (int p = 1; p < Database.Main.length("black") + 1; p++)
        {

            Player current = new Player(Database.Main.get(p, "name", "black"), Integer.parseInt(Database.Main.get(p, "num", "black")), Integer.parseInt(Database.Main.get(p, "pos", "black")), GUI.getTeam(4));
            for (Game g : GUI.getTeam(4).getGames())
            {
                current.addGame(g);
            }
            data[p] = current.averages();
        }

        for (int row = 0; row<data.length; row++)
        {
            for (int column = 0; column<data[row].length; column++)
            {
                output = output + data[row][column] + "\t       ";
            }
            output = output + "\n";
        }
        stats = new javax.swing.JTextArea(output);
        jScrollPane1 = new javax.swing.JScrollPane();
        String result = "";
        String[][] dataset = new String[2][5];

        Team team = GUI.getTeam(4);
        for (Game g : GUI.getTeam(4).getGames())
        {
            team.addGame(g);
        }
        dataset[1] = team.average();

        String[] categories = {"PPG", "Opp PPG", "Pace", "OffRtg", "DefRtg"};
        dataset[0] = categories;

        for (int row = 0; row<dataset.length; row++)
        {
            for (int column = 0; column<dataset[row].length; column++)
            {
                result = result + dataset[row][column] + "\t       ";
            }
            result = result + "\n";
        }
        advancedStats = new javax.swing.JTextArea(result);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        TeamsText.setFont(new java.awt.Font("Trebuchet MS", 0, 28)); // NOI18N
        TeamsText.setText("Black Army U17");

        players.setText("Players");

        advanced.setText("Advanced");

        BlackLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mock/1535466143.png"))); // NOI18N
        BlackLogo1.setLocation(new java.awt.Point(-32720, -32290));

        stats.setEditable(false);
        stats.setColumns(20);
        stats.setRows(5);
        jScrollPane3.setViewportView(stats);

        advancedStats.setColumns(20);
        advancedStats.setRows(5);
        jScrollPane1.setViewportView(advancedStats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(players, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(advanced))
                        .addContainerGap(547, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BlackLogo1)
                        .addGap(18, 18, 18)
                        .addComponent(TeamsText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton)
                            .addComponent(BlackLogo1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(TeamsText)))
                .addGap(18, 18, 18)
                .addComponent(players, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(advanced)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GUIForm obj;
        try {
            obj = new GUIForm();
            obj.setVisible(true);
            close();
        } catch (Exception ex) {
            Logger.getLogger(Black.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_backButtonActionPerformed

    public void close()
    {
        this.setVisible(false);
        this.dispose();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Black.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Black.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Black.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Black.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Black().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Black.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlackLogo1;
    private javax.swing.JLabel TeamsText;
    private javax.swing.JLabel advanced;
    private javax.swing.JTextArea advancedStats;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel players;
    private javax.swing.JTextArea stats;
    // End of variables declaration//GEN-END:variables
}
