/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mock.ia;


import java.util.logging.Level;
import java.util.logging.Logger;

        
/**
 *
 * @author tito
 */
public class GUIForm extends javax.swing.JFrame {

     
    private Blue blue;
    private Red red;
    private White white;
    private Black black;
   
    private SearchParser search;
    private InputGame inputGame;
    
    /**
     * Creates new form GUIForm
     */
    public GUIForm() throws Exception{
        initComponents();       
    }
    
    /**
     * Setter method for blue
     * @param blue 
     */
    public void setBlue(Blue blue)
    {
        this.blue = blue;
    }
    
    /**
     * Setter method for red
     * @param red 
     */
    public void setRed(Red red)
    {
        this.red = red;
    }
    
    /**
     * Setter method for white
     * @param white 
     */
    public void setWhite(White white)
    {
        this.white = white;
    }
    
    /**
     * Setter method for black
     * @param black 
     */
    public void setBlack(Black black)
    {
        this.black = black;
    }
   
    /**
     * Setter method for the advanced searcher
     * @param search 
     */
    public void setSearcher(SearchParser search)
    {
        this.search = search;
    }
    
    /**
     * Setter method for inputGame
     * @param inputGame 
     */
    public void setInputGame(InputGame inputGame)
    {
        this.inputGame = inputGame;
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BlackButton1 = new javax.swing.JButton();
        BlueLogo1 = new javax.swing.JLabel();
        WhiteLogo1 = new javax.swing.JLabel();
        RedLogo1 = new javax.swing.JLabel();
        BlackLogo1 = new javax.swing.JLabel();
        LeagueLogo1 = new javax.swing.JLabel();
        TeamsText1 = new javax.swing.JLabel();
        BlueButton1 = new javax.swing.JButton();
        WhiteButton1 = new javax.swing.JButton();
        RedButton1 = new javax.swing.JButton();
        input = new javax.swing.JButton();
        advancedSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BlackButton1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        BlackButton1.setText("Black Army U17");
        BlackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackButton1ActionPerformed(evt);
            }
        });

        BlueLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mock/1535466171.png"))); // NOI18N
        BlueLogo1.setText("jLabel2");

        WhiteLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mock/1535466320.png"))); // NOI18N

        RedLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mock/1535466251.png"))); // NOI18N
        RedLogo1.setLocation(new java.awt.Point(-32716, -32480));

        BlackLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mock/1535466143.png"))); // NOI18N
        BlackLogo1.setLocation(new java.awt.Point(-32720, -32290));

        LeagueLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mock/1441545576.png"))); // NOI18N

        TeamsText1.setFont(new java.awt.Font("Trebuchet MS", 0, 28)); // NOI18N
        TeamsText1.setText("Teams");

        BlueButton1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        BlueButton1.setText("Blue Army U17");
        BlueButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueButton1ActionPerformed(evt);
            }
        });

        WhiteButton1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        WhiteButton1.setText("White Army U17");
        WhiteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhiteButton1ActionPerformed(evt);
            }
        });

        RedButton1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        RedButton1.setText("Red Army U17");
        RedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedButton1ActionPerformed(evt);
            }
        });

        input.setText("New Game");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        advancedSearch.setText("Advanced Search");
        advancedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LeagueLogo1)
                        .addGap(18, 18, 18)
                        .addComponent(TeamsText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(input)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BlueLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WhiteLogo1)
                            .addComponent(RedLogo1)
                            .addComponent(BlackLogo1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BlueButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RedButton1)
                                    .addComponent(WhiteButton1)
                                    .addComponent(BlackButton1))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(advancedSearch)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeamsText1)
                            .addComponent(LeagueLogo1)))
                    .addComponent(input))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BlueLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlueButton1))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WhiteLogo1)
                    .addComponent(WhiteButton1))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RedLogo1)
                    .addComponent(RedButton1))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BlackButton1)
                    .addComponent(BlackLogo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(advancedSearch)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Used to switch JFrames
     */
    public void close()
    {
        this.setVisible(false);
        
    }
    
    /**
     * Switches to Blue JFrame
     * @param evt 
     */
    private void BlueButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueButton1ActionPerformed
        // TODO add your handling code here:

        try {
            blue.setVisible(true);
            close();
        } catch (Exception ex) {
            Logger.getLogger(GUIForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BlueButton1ActionPerformed

    /**
     * Switches to Red JFrame
     * @param evt 
     */
    private void RedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            red.setVisible(true);
            close();
        } catch (Exception ex) {
            Logger.getLogger(GUIForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_RedButton1ActionPerformed

    /**
     * Switches to White JFrame
     * @param evt 
     */
    private void WhiteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhiteButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            white.setVisible(true);
            close();
        } catch (Exception ex) {
            Logger.getLogger(GUIForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_WhiteButton1ActionPerformed

    /**
     * Switches to Black JFrame
     * @param evt 
     */
    private void BlackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackButton1ActionPerformed
        // TODO add your handling code here:

        try {
            black.setVisible(true);
            close();
        } catch (Exception ex) {
            Logger.getLogger(GUIForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BlackButton1ActionPerformed

    /** 
     * Switches to inputGame JFrame
     * @param evt 
     */
    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
       
        inputGame.setVisible(true);
        close();
    }//GEN-LAST:event_inputActionPerformed

    /**
     * Switches to the advanced searcher JFrame
     * @param evt 
     */
    private void advancedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedSearchActionPerformed
        // TODO add your handling code here:
        
        search.setVisible(true);
        close();
    }//GEN-LAST:event_advancedSearchActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUIForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(GUIForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackButton1;
    private javax.swing.JLabel BlackLogo1;
    private javax.swing.JButton BlueButton1;
    private javax.swing.JLabel BlueLogo1;
    private javax.swing.JLabel LeagueLogo1;
    private javax.swing.JButton RedButton1;
    private javax.swing.JLabel RedLogo1;
    private javax.swing.JLabel TeamsText1;
    private javax.swing.JButton WhiteButton1;
    private javax.swing.JLabel WhiteLogo1;
    private javax.swing.JButton advancedSearch;
    private javax.swing.JButton input;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
